// <auto-generated />
namespace Dating.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedtwomoreproponeforsexualPrerenceandanotherforidentitybothlinkedtotheuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtwomoreproponeforsexualPrerenceandanotherforidentitybothlinkedtotheuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201909261416002_added-two-more-prop-one-for-sexualPrerence-and-another-for-identity-both-linked-to-the-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
