// <auto-generated />
namespace Dating.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedgeocodemodelwiththeneededprprtiesalsoaddedlatitudeandlogitudepropertestopersonmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedgeocodemodelwiththeneededprprtiesalsoaddedlatitudeandlogitudepropertestopersonmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201910172136015_added geocode model with the needed prprties, also added latitude and logitude propertes to person model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
