// <auto-generated />
namespace Dating.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class madebothPersonIdandPersonIdnulleble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madebothPersonIdandPersonIdnulleble));
        
        string IMigrationMetadata.Id
        {
            get { return "201909301924448_made both Person Id and PersonId nulleble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
